spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.cointda/h2/cointdadbtest;AUTO_SERVER=TRUE
    username: root
    password: test
  sql:
    init:
      mode: always
      platform: h2
      #data-locations: classpath:db/data-h2.sql
      schema-locations: classpath:db/schema-h2.sql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增