spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.cointda/h2/cointdadbtest;AUTO_SERVER=TRUE
    username: root
    password: test
  sql:
    init:
      mode: always
      platform: h2
      #data-locations: classpath:db/data-h2.sql
      schema-locations: classpath:db/schema-h2.sql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增

coin-market-cap:
  apiKey: 8f94c3a3-0a31-43e4-818e-a7e83791b1b3
  customHeader: X-CMC_PRO_API_KEY
  httpHeader: application/json
  coinMarketCapIDMap: https://pro-api.coinmarketcap.com/v1/cryptocurrency/map
  #metadata: https://pro-api.coinmarketcap.com/v1/cryptocurrency/info
  latestlistings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  #historicalListings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/historical
  latestQuotes: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
  #historicalQuotes: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical
  #latestMarketPairs: https://pro-api.coinmarketcap.com/v1/cryptocurrency/market-pairs/latest -
  #latestOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/latest
  #historicalOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical
  #pricePerformanceStats: https://pro-api.coinmarketcap.com/v1/cryptocurrency/price-performance-stats/latest
